### ISSUE TITLE
restart variable sal_ice does not reproduce across a restart

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/SIS2#114]
sal_ice differs across a restart (i.e., in 1x2day test and 2x1day test ice_model.res.nc)
This flags automated restart tests as failed.

Given that sal_ice is the only variable that does not match across a restart, it probably does not belong to the restart file.

To reproduce run any test case (e.g.,  Baltic) with a restart and compare the ice_model.res.nc

**Comment by Hallberg-NOAA** [comment]
I have just re-tested this with the latest version of SIS2, and I am finding that the values of sal_ice in the restart files do match.

  I do not know when this problem got fixed, but if this is still found to be a problem, please re-open this issue, along with the details of the version of the model that is not reproducing across restarts.
