### ISSUE TITLE
Trouble reproducing SIS2 restart runs with new IO

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/SIS2#118]
I've been updating the SIS2 routines to use the new IO to read and write restart files on the branch [user/jml/add_new_fms_io_02](https://github.com/wrongkindofdoctor/SIS2/tree/user/jml/add_new_fms_io_02). I am able to write restart files that reproduce the unmodified code in a cold start SIS2 run (6--30 pes). However, when I run the same experiment initializing from restart files,  the answers diverge from the unmodified code after initialization. It appears that I am reading the data in correctly, as the data buffers match at the end of [ice_model_init](https://github.com/wrongkindofdoctor/SIS2/blob/4a4534b3e67b76c5c4b611f2b129afd0f47fb889/src/ice_model.F90#L1595). 

I suspect the divergence occurs because I have ordered the registration calls improperly; all registration routines need to be called twice--once for the file being written, and once for the file being read--because the netcdf methods and data occupy the same structure in the new IO. As a result, I had to modify [ice_model](https://github.com/wrongkindofdoctor/SIS2/blob/user/jml/add_new_fms_io_02/src/ice_model.F90), [ice_type](https://github.com/wrongkindofdoctor/SIS2/blob/user/jml/add_new_fms_io_02/src/ice_type.F90), and [SIS_types](https://github.com/wrongkindofdoctor/SIS2/blob/user/jml/add_new_fms_io_02/src/SIS_types.F90) extensively to deal with different file objects in read or write/overwrite/append mode. 

I have been working on this for two weeks, and have made zero progress because I don't know exactly how the calls need to be ordered, and/or if I have not set up the fast and slow pointers correctly.  I would appreciate any insight @adcroft, @nikizadehgfdl, or @marshallward  can offer.

I've submitted a draft PR #117  so you can more easily see the changes I've made to the code.

**Comment by nikizadehgfdl** [comment]
@wrongkindofdoctor The usual way to debug this is to set DEBUG=True in SIS_override and MOM_override and run the two simulations (with and without your mods) for one day. Then If you compare the two stdouts you can usually find where they diverge. 

Also, some (not all) coupler_init ice_data checksums printed at stout must match between the two runs (in normal runs without DEBUG=True ). 

Also, note that the restart values on Land could change the answers, so make sure to read the land values consistently. 

If you point me to the two workdirs I'll take a look.

**Comment by wrongkindofdoctor** [comment]
Thank you, @nikizadehgfdl.  I will try using the debug setting in the override namelists as suggested, and send you the directory paths if I'm still having trouble.

**Comment by Hallberg-NOAA** [comment]
The new PR https://github.com/NOAA-GFDL/SIS2/pull/144 extensively revises the SIS2 restart capability to work via the code in the MOM6 src/framework and config_src/infra directories.  This new code reproduces answers across restarts, either for single-file or decomposed restart files, and does so when the calls eventually resolve to either the FMS2 or the original FMS routines, depending on which directory under config_src/infra/FMS[12] is used.  This issue is therefore no longer relevant to SIS2.
