### ISSUE TITLE
CM4_c96L48_am4a3_2000_sis2 crashed at day 461 with Sea ice velocity has been truncated too many times.

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/SIS2#16]
I made a production run of  CM4_c96L48_am4a3_2000_sis2   ( as a way of testing fre). The model crashed after a year with

```
 FATAL from PE     0: write_ice_statistics: Sea ice velocity has been truncated too many times.

SIS Day  461.500   2316: Area 1.346150078628E+13 1.433465489267E+12, Mass  1.44594418326E+16 3.09536575974E+14
SIS Day     461.500 Sea Ice Truncations 6
 Total Ice Mass:   1.4768978408535282E+16, Change:  1.13720E+13 Error:  1.81835E-02 ( 1.2E-18)
 Total Ice Salt:   4.3259800059488441E+10, Change:  3.42388E+07 Error:  6.01789E-08 ( 1.4E-18)
 Total Ice Heat:  -4.9565853328454944E+21, Change: -5.59417E+18 Error:  5.81362E+05 (-1.2E-16)
```

stdout:

/lustre/f1/Niki.Zadeh/ulm_mom6_2015.03.13/CM4_c96L48_am4a3_2000_sis2/ncrc2.intel-prod-openmp/stdout/run/CM4_c96L48_am4a3_2000_sis2.o5040960

workdir:
/lustre/f1/Niki.Zadeh/work/ulm_mom6_2015.03.13/CM4_c96L48_am4a3_2000_sis2.o5040960

This experiment is from the xml that I prepared for Bill.
If this configuration is not valid please let me know so that I can remove it from the xml.

**Comment by adcroft** [comment]
Commits 57774fa616f974552cc720741f942a2236f2d2ef, 500fdd4cbc5d51e538c0fe9a2c7bc2e916a868ed and 5a49e3026d4d6703d0c03ad6498a5deaf65e99c9, along with all the MOM6 fixes seems to have cleared up any instances of this kind of crash.
