### ISSUE TITLE
Unhelpful error message if asking for DO_RIDGING without Icepack linked in

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/SIS2#183]
If asking for DO_RIDGING without Icepack, one gets:
```
FATAL from PE    14: nilyr or nslyr mismatch with Icepack
```
It would be nice to having it instead say that DO_RIDGING is not available without linking in Icepack/columnphysics.

**Comment by MJHarrison-GFDL** [comment]
Thanks for pointing this out @kshedstrom .  It is an accurate, but useless error message.  I will send a PR with a more useful message informing that actual Icepack code needs to be included in the compilation of the model, rather than the stub code in config_src/external

**Comment by Hallberg-NOAA** [comment]
This issue was addressed by https://github.com/NOAA-GFDL/SIS2/pull/184, and can now be closed.
