### ISSUE TITLE
sis2 does not compile with -openmp

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/SIS2#26]
There is an openmp compile issue in the  release tag of 2015.10.02 

```
/lustre/f1/Niki.Zadeh/testing_20151009_mom6_2015.10.02/MOM6_CM_libs_compile/src/mom6/src/SIS2/SIS_tracer_advect.F90(492): error #6752: Since the OpenMP* DEFAULT(NONE) clause applies, the PRIVATE, SHARED, REDUCTION, FIRSTPRIVATE, or LASTPRIVATE attribute must be explicitly specified for every variable.   [DOMORE_U]
        domore_u(j, k) = .false.
--------^
```

**Comment by adcroft** [comment]
I am able to compile dev/master/2015.10.13 using Intel-12. Is this an Intel-14 issue?

**Comment by nikizadehgfdl** [comment]
Both intel-12 and intel-14, it's the usual OMP bug. You have to compile with -openmp to catch it.

There are also a few similar  openmp issues in MOM6
```
/lustre/f1/Niki.Zadeh/testing_20151009_mom6_2015.10.13/MOM6_CM_libs_compile/src/mom6/src/MOM6/src/ALE/MOM_regridding.F90(277): error #6404: This name does not have a type, and must have an explicit type.   [NZ]
!$OMP parallel do default(none) shared(G,nz,h,dzInterface,eps) &
-----------------------------------------^
```

**Comment by adcroft** [comment]
Yes - I fixed MOM6 this morning (will push later) but I don't get any SIS2
errors.

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by nikizadehgfdl** [comment]
There are still issues with sis2 compiling with -openmp in two files SIS_tracer_advect.F90 and ice_model.F90
I fixed them in user/nnz/fix_omp_compile

**Comment by adcroft** [comment]
@nikizadehgfdl Am I correct in thinking #28 closes this issue?

**Comment by nikizadehgfdl** [comment]
dev/master sis2 (2016/01/12) compiles with -openmp
