### ISSUE TITLE
test case MOM6_GOLD_SIS2_bergs crashed with seg. fault. when compiled with intel 14 on gaea in prod mode

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/SIS2#27]
In the most recent branch of MOM6 2015.10.13 the test case MOM6_GOLD_SIS2_bergs crashed with seg. fault.

```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
fms_MOM6_SIS2_com  0000000001987050  Unknown               Unknown  Unknown
fms_MOM6_SIS2_com  00000000004BC99A  ice_model_mod_mp_        2131  ice_model.F90
fms_MOM6_SIS2_com  0000000000497B1B  ice_model_mod_mp_         135  ice_model.F90
fms_MOM6_SIS2_com  0000000000402C37  MAIN__                    875  coupler_main.F90
```

This was compiled with intel14. I have not tried intel12 yet.

**Comment by nikizadehgfdl** [comment]
There is no such issue with intel 12. In all likelihood there is something wrong with my build. 
I assign to myself till I figure it out.

**Comment by nikizadehgfdl** [comment]
The seg. fault  happened again (for the 3rd time) with intel14 compiler.

**Comment by nikizadehgfdl** [comment]
I have another experiment AM2_LM3_SIS2B_MOM6i_1deg  crashing exactly like this.

**Comment by nikizadehgfdl** [comment]
This happens only for the prod mode (-O3). The debug and repro modes do not hit this issue.

**Comment by Hallberg-NOAA** [comment]
Hi,
    
     For a report like this where there is a strong potential for this
    to be machine or compiler specific, it is important that we include
    the compiler version and machine with each message.  Is this still
    restricted to being a problem with the Intel-14 compiler?
    
      - Bob Hallberg
    
    On 10/16/2015 06:29 PM, Niki Zadeh wrote:
    
      This happens only for the prod mode (-O3). The debug and repro
        modes do not hit this issue.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by nikizadehgfdl** [comment]
Yes this is restricted to Intel-14. And it is on gaea.

**Comment by nikizadehgfdl** [comment]
Intel 14 is long wiped from gaea and no such issues with Intel15 or later. Closing.
