### ISSUE TITLE
Missing a mpp_clock_begin

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/SIS2#29]
Message received from Will Cooke:

In the 04f566a version of SIS2 (~1/20/16 version), there is a missing mpp_clock_begin.

If you set clock_grain to 'LOOP', it should fail in the main loop at line 2052 of ice_model.F90
```
call set_ocean_top_stress_Cgrid(Ice, IST, WindStr_x_ocn_Cu, WindStr_y_ocn_Cv, &
  str_x_ice_ocn_Cu, str_y_ice_ocn_Cv, IST%part_size, G)
call mpp_clock_end(iceClockc)
```
I'm not sure where iceClockc needs to be begun.
If you've caught this already, then never mind.

Will

**Comment by Hallberg-NOAA** [comment]
This issue was corrected with commit NOAA-GFDL/SIS2@2138434a01acf635986986419be15ff05e06f7d8.
