### ISSUE TITLE
missing do-loop in ice_model.F90 

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/SIS2#33]
On line 2665 and 2666 of ice_model.F90 there is a k index but no associated do-loop.

```
    do j=jsc,jec ; do i=isc,iec
      T_col(0) = Temp_from_En_S(IST%enth_snow(i,j,k,1), 0.0, IST%ITV)
      do m=1,NkIce ; T_col(m) = Temp_from_En_S(IST%enth_ice(i,j,k,m), S_col(m), IST%ITV) ; enddo
```

Is this meant to inherit k=ncat+1 from the previous k-loop or is the loop missing ?!

**Comment by Hallberg-NOAA** [comment]
@nikizadehgfdl fixed this issue with commit 53991cda95480fd52dc0dfe9e9fd429783335bb0
