### ISSUE TITLE
Compilation error in ice_model.F90

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/SIS2#39]
I'm not sure why I'm getting this and no one else...

mpifort -Duse_libMPI -Duse_netCDF -DSPMD -DUSE_LOG_DIAG_FIELD_INFO -Duse_AM3_physics -Duse_LARGEFILE   -fcray-pointer -fdefault-real-8 -fdefault-double-8 -Waliasing -ffree-line-length-none -fno-range-check -O0 -g -W -fbounds-check  -I../../../shared/DEBUG  -c -I../../../../../src/MOM6/config_src/dynamic_symmetric -I../../../../../src/MOM6/src/framework	../../../../../src/MOM6/src/core/MOM_dynamics_legacy_split.F90
../../../../../src/SIS2/ice_model.F90:330.51:

  call pass_vector(IST%flux_u_top, IST%flux_v_top, G%Domain, stagger=AGRID)
                                                   1
Error: Procedure argument at (1) is INTENT(IN) while interface specifies INTENT(INOUT)
make: *** [ice_model.o] Error 1
make: *** Waiting for unfinished jobs....

This was introduced in:
commit c12c79494f062a587089425818ca27882d513049
Author: Robert Hallberg <Robert.Hallberg@noaa.gov>
Date:   Tue Jul 19 18:25:43 2016 -0400

    +Split avg_top_quantities and post_flux_diagnostics

**Comment by nicjhan** [comment]
mpifort -Duse_libMPI -Duse_netCDF -DSPMD -DUSE_LOG_DIAG_FIELD_INFO -Duse_AM3_physics  -fpp -Wp,-w -I/include -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -I/include -g -O0 -check -check noarg_temp_created -check nopointer -warn -warn noerrors -fpe0 -traceback -ftrapuv -assume nobuffered_io -I../../../shared/DEBUG  -c -I../../../../../src/SIS2 -I../../../../../src/MOM6/src/framework	../../../../../src/SIS2/SIS_fast_thermo.F90
../../../../../src/SIS2/SIS_fast_thermo.F90(258): error #6780: A dummy argument with the INTENT(IN) attribute shall not be defined nor become undefined.   [G]
  call pass_vector(FIA%flux_u_top, FIA%flux_v_top, G%Domain, stagger=AGRID)
---------------------------------------------------^
compilation aborted for ../../../../../src/SIS2/SIS_fast_thermo.F90 (code 1)
make: *** [SIS_fast_thermo.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by Hallberg-NOAA** [comment]
These incorrect declarations of intent have been fixed in commit NOAA-GFDL/SIS2@cc99fb271d654b494c2ac05adce86f94678ad092.
