### ISSUE TITLE
No output for SLP diagnostic

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/SIS2#40]
The SLP diagnostic does not work. Fix on the way.

**Comment by nicjhan** [comment]
https://github.com/NOAA-GFDL/SIS2/pull/41

**Comment by Hallberg-NOAA** [comment]
https://github.com/nicjhan corrected this issue with commit NOAA-GFDL/SIS2@218f0de21bc82cd10f22a34cb8ab0c930e1845f2 .
