### ISSUE TITLE
restart variable T_skin does not reproduce across pe counts

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/SIS2#61]
For the test case ice_ocean_SIS2/SIS2_icebergs , the new variable T_skin does not reproduce between different pe counts (30, 32, 128). 
The difference pattern is strange and jumps from -1.98 to +1.98 at some locations.

**Comment by nikizadehgfdl** [comment]
ice_ocean_SIS2/SIS2_icebergs does not reproduce across restart either (MOM.res.nc differ across restart too). However ice_ocean_SIS2/SIS2_bergs_cgrid does reproduce across both pe change and restart.

**Comment by Hallberg-NOAA** [comment]
This issue was closed as a result of bug fixes in SIS2 commits NOAA-GFDL/SIS2@4cecaccb69fc388bc5e8f4d6732b25d1db77c176 and  NOAA-GFDL/SIS2@69ed8df8c6a8a190bcb30e8c8b11879b2322a8ac.
