### ISSUE TITLE
CMIP requests Sea-ice and snow concentration in % (not 0-1)

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/SIS2#91]
Units for sea-ice concentration (siconc) and sea-ice snow concentration (sisnconc) are currently fractional (0-1) while the CMIP6 data request specifies the output be in %.

siconc: http://clipc-services.ceda.ac.uk/dreq/u/150ada98-357c-11e7-8257-5404a60d96b5.html
sisnconc: http://clipc-services.ceda.ac.uk/dreq/u/590d38b0-9e49-11e5-803c-0d0b866b59f3.html

While this can be corrected in post-processing, updating it in the model would provide a more permanent fix.

**Comment by Hallberg-NOAA** [comment]
We should add a different diagnostic with units of percent and using the CMOR variable name.

**Comment by Hallberg-NOAA** [comment]
SIS2 PR #146 added the new variables siconc_CMOR and sisnconc_CMOR that use the recommended CMOR units.
