### ISSUE TITLE
SIS2 ignores the input_filename in input_nml

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/SIS2#96]
@Hallberg-NOAA , @wfcooke , @MJHarrison-GFDL 
When I set input_filename = 'r'  AND do not provide any INPUT/ice_model.res.nc
the model does not complain (unlike MOM6 behavior).
Also when I set input_filename = 'n' AND provide a INPUT/ice_model.res.nc
the model does not complain and reads the restart (unlike MOM6 behavior).
This is a change in behavior that confuses users and may cause models to do something wrong for those who depend on that logic.

Please verify if this is the new feature or a bug.

Also, it would be helpful if the stdout or some log file showed whether ice restart file(s) were actually read in a run.

**Comment by Hallberg-NOAA** [comment]
This issue was addressed by PR #141.
